// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZjtnDyxUFzGRwajGM-B3hH2ThSEwSpww',
    appId: '1:146158861969:web:3df2b2c5f47679373b8930',
    messagingSenderId: '146158861969',
    projectId: 'dalel-b25fd',
    authDomain: 'dalel-b25fd.firebaseapp.com',
    storageBucket: 'dalel-b25fd.appspot.com',
    measurementId: 'G-9Q6V50YQZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Ex2pwzYMXjSbMwzBgzJdYXidkg7TJTY',
    appId: '1:146158861969:android:6b9f41e9d75cfde03b8930',
    messagingSenderId: '146158861969',
    projectId: 'dalel-b25fd',
    storageBucket: 'dalel-b25fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPccAH-RRQ425LT8Binr1kPKmFI2AfpNg',
    appId: '1:146158861969:ios:69eba1b116bb430e3b8930',
    messagingSenderId: '146158861969',
    projectId: 'dalel-b25fd',
    storageBucket: 'dalel-b25fd.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPccAH-RRQ425LT8Binr1kPKmFI2AfpNg',
    appId: '1:146158861969:ios:69eba1b116bb430e3b8930',
    messagingSenderId: '146158861969',
    projectId: 'dalel-b25fd',
    storageBucket: 'dalel-b25fd.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZjtnDyxUFzGRwajGM-B3hH2ThSEwSpww',
    appId: '1:146158861969:web:03bf756ac78d29f93b8930',
    messagingSenderId: '146158861969',
    projectId: 'dalel-b25fd',
    authDomain: 'dalel-b25fd.firebaseapp.com',
    storageBucket: 'dalel-b25fd.appspot.com',
    measurementId: 'G-0BG5KS79Y5',
  );
}
